export const TAGS = {
  SITE: {
    FUR4: '@site:fur4',
    REFER: '@site:refer',
  },
  MODULE: {
    FUR4: {
      AUTH: '@fur4:auth',
      CHECKOUT: '@fur4:checkout',
      NAV: '@fur4:navigation',
      DEALER: '@fur4:dealer',
      SOCIAL: '@fur4:social',
    },
    REFER: {
      AUTH: '@refer:auth',
      NAV: '@refer:navigation',
      SOCIAL: '@refer:social',
      REWARD: '@refer:reward',
    },
  },
  CASE: {
    FUR4: {
      F001: '@fur4:001',
      F002: '@fur4:002',
      F003: '@fur4:003',
      F004: '@fur4:004',
    },
    REFER: {
      R001: '@refer:001',
      R002: '@refer:002',
      R003: '@refer:003',
      R004: '@refer:004',
    },
  },
};

export enum Type {
  FUNCTIONAL = '@FUNCTIONAL',
  FUNCTIONALITY = '@FUNCTIONALITY',
  SMOKE = '@SMOKE',
  LOAD = '@LOAD',
  HEADER = '@HEADER',
  VISUAL = '@VISUAL',
  BRANDING = '@BRANDING',
  HERO = '@HERO',
  CONTENT = '@CONTENT',
  IMAGE = '@IMAGE',
  BUTTON = '@BUTTON',
  ICON = '@ICON',
  MENU = '@MENU',
  NAVIGATION = '@NAVIGATION',
  NAV = '@NAV',
  AUTH = '@AUTH',
  WIDGET = '@WIDGET',
  CHAT = '@CHAT',
  FOOTER = '@FOOTER',
  UI = '@UI',
  TOOLTIP = '@TOOLTIP',
  LAYOUT = '@LAYOUT',
  USABILITY = '@USABILITY',
  SECTION = '@SECTION',
  SCROLL = '@SCROLL',
  NEWSLETTER = '@NEWSLETTER',
  INPUT = '@INPUT',
  VALIDATION = '@VALIDATION',
  SUBSCRIPTION = '@SUBSCRIPTION',
  OVERLAY = '@OVERLAY',
  DROPDOWN = '@DROPDOWN',
  CART = '@CART',
  PRODUCTS = '@PRODUCTS',
  VIDEO = '@VIDEO',
  BANNER = '@BANNER',
  LINK = '@LINK',
  PAGE_LOAD = '@PAGE_LOAD',
  RESPONSIVE = '@RESPONSIVE',
  MOBILE = '@MOBILE',
  SEO = '@SEO',
  ACCESSIBILITY = '@ACCESSIBILITY',
  // Additional types for dealer-locator tests
  MAP = '@MAP',
  FORM = '@FORM',
  NEGATIVE = '@NEGATIVE',
  SEARCH = '@SEARCH',
  BROWSER = '@BROWSER',
  LOCATION = '@LOCATION',
  DATA = '@DATA',
  DYNAMIC = '@DYNAMIC',
} 